### ISSUE TITLE
failure to get list of workflows

### ISSUE THREAD

**Issue by tomschlick** [rokroskar/workflow-run-cleanup-action#1]
I'm trying to run this and the entrypoint script is failing to get the list of workflows from the API. Below is my config, and below that is the output (with redacted repo names).

```
  cancel-previous-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

```
Run rokroskar/workflow-run-cleanup-action@master
/usr/bin/docker run --name dfb0f982190e4494381af39cf546d0aefc1_1d3b03 --label 488dfb --workdir /github/workspace --rm -e GITHUB_TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/--REDACTED--/--REDACTED--":"/github/workspace" 488dfb:0f982190e4494381af39cf546d0aefc1
+ '[' -z CI ']'
+ '[' -z *** ']'
+ '[' -z --REDACTED--/--REDACTED-- ']'
+ jq_workflow_id='.workflows |.[]| select(.name=="CI") .id'
+ jq_run_id='.workflow_runs | .[] | select(.head_branch=="chore/cancel-previous-branch-builds" and .status=="in_progress") | .id'
+ GITHUB_API=https://api.github.com
+ auth_header='Authorization: token ***'
++ jq '.workflows |.[]| select(.name=="CI") .id'
++ curl -s https://api.github.com/repos/--REDACTED--/--REDACTED--/actions/workflows -H Authorization: token ***
jq: error (at <stdin>:4): Cannot iterate over null (null)
+ workflow_id=
+ echo 'workflow id: '
++ curl -s https://api.github.com/repos/--REDACTED--/--REDACTED--/actions/workflows//runs -H Authorization: token ***
++ jq '.workflow_runs | .[] | select(.head_branch=="chore/cancel-previous-branch-builds" and .status=="in_progress") | .id'
jq: error (at <stdin>:4): Cannot iterate over null (null)
+ run_ids=
+ echo 'run ids: '
workflow id: 
run ids: 
```

My first thought here is that the `secrets.GITHUB_TOKEN` that [github provides per job](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token) doesn't have permissions. Would I need to generate a personal access token for this manually?

**Comment by rokroskar** [comment]
can you try the curl that retrieves the workflows with a personal access token? The github actions token should have the necessary permissions though. 

I guess I should also turn off the debug logging... :)

**Comment by tomschlick** [comment]
It looks like if I use a personal access token (with the `-u username:token` params instead of the authorization header) it does work. 

So my guess is that the action's `GITHUB_TOKEN` env var doesn't have permission which falls in line with this: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token

We might be able to ask the github developer who mentioned the new API in the forums if they can add the actions api to the list of permissions. Or else this might have to be configurable to use the `-u` auth method for personal access tokens.

**Comment by rokroskar** [comment]
Thanks for looking into it @tomschlick! I am using the standard `GITHUB_TOKEN` in my own repo and it seems to work. But it's true that I am running this on a public repo and those endpoints do not require authentication for a public repo - I haven't tried it on a private one. Would be great if you followed up in the forum!

**Comment by tomschlick** [comment]
I pinged the dev here: https://github.community/t5/GitHub-Actions/Github-actions-Cancel-redundant-builds/m-p/44872#M5953

**Comment by tomschlick** [comment]
Apparently the token should already have permissions: https://github.community/t5/GitHub-Actions/Github-actions-Cancel-redundant-builds/m-p/44873#M5954

So not sure what is going on there. It might be helpful if the json output of the API was outputted for debug purposes.

**Comment by rokroskar** [comment]
@tomschlick I had forgotten quotes around the `auth_header` variable - I just pushed a commit that should fix it, can you try again?

**Comment by tomschlick** [comment]
@rokroskar that does get the list correctly but it fails further down the line; likely due to a space + another number in the workflow id. 

```
/usr/bin/docker run --name dfb7f919f051ab04df49f71f133224b883b_2ac736 --label 488dfb --workdir /github/workspace --rm -e GITHUB_TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/--REDACTED--/--REDACTED--":"/github/workspace" 488dfb:7f919f051ab04df49f71f133224b883b
+ '[' -z CI ']'
+ '[' -z *** ']'
+ '[' -z --REDACTED--/--REDACTED-- ']'
+ jq_workflow_id='.workflows |.[]| select(.name=="CI") .id'
+ jq_run_id='.workflow_runs | .[] | select(.head_branch=="chore/cancel-previous-branch-builds" and .status=="in_progress") | .id'
+ GITHUB_API=https://api.github.com
+ auth_header='Authorization: token ***'
++ curl -s https://api.github.com/repos/--REDACTED--/--REDACTED--/actions/workflows -H 'Authorization: token ***'
++ jq '.workflows |.[]| select(.name=="CI") .id'
+ workflow_id='163727
workflow id: 163727 3472
3472'
run ids: 
+ echo 'workflow id: 163727' 3472
++ curl -s ++ jq '.workflow_runs | .[] | select(.head_branch=="chore/cancel-previous-branch-builds" and .status=="in_progress") | .id'
https://api.github.com/repos/--REDACTED--/--REDACTED--/actions/workflows/163727 3472/runs -H 'Authorization: token ***'
jq: error (at <stdin>:12): Cannot iterate over null (null)
+ run_ids=
+ echo 'run ids: '
```

**Comment by rokroskar** [comment]
Ah apparently a workflow name can match multiple workflow IDs - makes sense I guess. I assumed that wouldn't be the case, but I'll need to make it a bit more robust. PRs welcome of course if you come up with a solution in the meantime! :)

**Comment by rokroskar** [comment]
@tomschlick could you give me a guess as to how you end up with two IDs for the same workflow? Did you have the same name in two different workflow files? I'd like to reproduce the problem so I can figure out the best solution. Thanks!

**Comment by tomschlick** [comment]
Not sure there. We were a beta tester so maybe something as a relic of that? Changed the name and all is working now.

**Comment by rokroskar** [comment]
Ok I think I'll add an option to specify the filename of the workflow, it might help isolate it. Hopefully GitHub adds the workflow id to the environment though, that would make fully unambiguous. Thanks!

**Comment by vilkg** [comment]
Hi! Getting the same issue; in my case, the workflow contains multiple jobs.

**Comment by rokroskar** [comment]
This is still a problem so I'm reopening it
