### ISSUE TITLE
Pull Request cancels target branch with same name and vice verca 

### ISSUE THREAD

**Issue by mustaphazorgati** [rokroskar/workflow-run-cleanup-action#13]
Hey there!

Currently (v0.3.0) this action behaves similar for pull requests and regular commits.
For pull requests the source branch of the pull request is regarded `BRANCH`.
For regular push events the branch of the repo is regarded `BRANCH`.
There is no other differentiation.

If a pull request source branch has the same name as a repo branch workflow runs on each of them will cancel each other out.

Expected behaviour: the pull request does not cancel the repo branch workflow, but other pull request (running) workflows. Same for the repo branch workflow.

**Comment by mustaphazorgati** [comment]
Hey @rokroskar!
I am willing to fix this. Beforehand I'd like to get your thoughts about this. So: What do you think?

**Comment by rokroskar** [comment]
Hi @mustaphazorgati thanks for opening this issue and apologies for missing it the first time around! 

I'm trying to understand the problem - I suppose you mean if a PR is open from a branch in a fork and the branch has the same name as a branch in the parent repo, then the two runs will cancel each other out when they shouldn't?

**Comment by mustaphazorgati** [comment]
> I'm trying to understand the problem - I suppose you mean if a PR is open from a branch in a fork and the branch has the same name as a branch in the parent repo, then the two runs will cancel each other out when they shouldn't?

Yes that's the issue. Just to make sure that we both are talking about the same thing I'll make an example.

I create a PR from `mustaphazorgati/workflow-run-cleanup-action:master` to `rokroskar/workflow-run-cleanup-action:master`. Since the branch name on my fork and on the "main" repository is `master` the workflow runs will cancel each other out. 

Did the example help?

**Comment by rokroskar** [comment]
Yes definitely, I see the problem. Would be very happy if you sent a PR to fix it! Thanks!

**Comment by mustaphazorgati** [comment]
I'll have a try over the weekend :)

**Comment by rokroskar** [comment]
Great, I look forward to it! 🚀
