### ISSUE TITLE
implement an environment variable for debug mode

### ISSUE THREAD

**Issue by rokroskar** [rokroskar/workflow-run-cleanup-action#2]
By default, the script should not run with `set -x` but it can be useful for debugging. So implement a `DEBUG` environment variable.

**Comment by mustaphazorgati** [comment]
this can be closed, right?

**Comment by mustaphazorgati** [comment]
Should be implemented with https://github.com/rokroskar/workflow-run-cleanup-action/pull/29

**Comment by rokroskar** [comment]
indeed, thanks!
