### ISSUE TITLE
Not found lastest version at marketplace

### ISSUE THREAD

**Issue by shmokmt** [rokroskar/workflow-run-cleanup-action#20]
![image](https://user-images.githubusercontent.com/32533860/111269114-82ded480-8671-11eb-9e50-76cfe9a72087.png)

I'd like to use latest version(v0.3.2) but it is not found in marketplace.

Could you release it to GitHub Marketplace?

**Comment by mustaphazorgati** [comment]
Hey @rokroskar,

this seems to be a short thing. <5 min.
According to this [documentation](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace) it's just a matter of checking a checkbox in the release.

**Comment by rokroskar** [comment]
Done! Thank you @mustaphazorgati and @shmokmt!
