### ISSUE TITLE
old workflow cancels newer one

### ISSUE THREAD

**Issue by mustaphazorgati** [rokroskar/workflow-run-cleanup-action#21]
Hey @rokroskar,

I just had the following situation:
I merged 3 PRs in quick succession. Because of this 3 workflows were created on the master branch of that repository. Because all 3 workflows were `queued` or `in progress` the first workflow cancelled the other two. Unfortunately the first workflow was not the latest. 
I'll make an example for clarification: 
I merged PR `A`, `B` and `C`. `A` ist the first PR I merged, `C` the last. 
Expected behaviour: Workflow `C` is the only one running.
Actual behaviour: Workflow `A` cancelled workflow `B` and `C` and was the only one running. 

Afterwards I inspected the workflows and realized that the `workflow_run_id` is an incrementing number. If we assume that statement we could add a little logic, so that workflows with a higher id will not be cancelled. And if any workflow with a higher id is detected the current workflow cancels itself too.

What do you think about this idea?

**Comment by rokroskar** [comment]
yes true, with the current logic there can be a concurrency problem. I think what you suggest makes sense!

**Comment by thofma** [comment]
I want to second what @mustaphazorgati said. I tried it for a week now and with commits at a high frequency often wrong runs were cancelled. I like the idea of the cleanup workflow, but with something like #21 it gets a lot closer to what it is meant to do.

**Comment by rokroskar** [comment]
Thanks for chiming in @thofma - apologies, I thought #22 had already been merged 🙈 I'll try to get to reviewing it today!

**Comment by thofma** [comment]
Thank you both!
