### ISSUE TITLE
Action cancels workflows on unrelated PRs.

### ISSUE THREAD

**Issue by dpp23** [rokroskar/workflow-run-cleanup-action#28]
I think the issue is on this line:

https://github.com/rokroskar/workflow-run-cleanup-action/blob/5fb07e770c6ee0d595c1fb8383b7af343428817f/entrypoint.sh#L32

and it should read:

```
 workflow_ids=$(jq ".workflow_runs | .[] | select(.head_branch==\"${branch?}\" and .head_repository.full_name==\"${repo?}\" and (.status==\"in_progress\" or .status==\"queued\" or .status== \"waiting\")) | .id ")
 ```

Opening an issue to confirm that I understood the expected behaviour correctly - I can submit a patch if I am correct.

**Comment by walterholohan** [comment]
Yes, I am experiencing the same issue

**Comment by mustaphazorgati** [comment]
Hey @dpp23,
thanks for noticing.

> Opening an issue to confirm that I understood the expected behaviour correctly - I can submit a patch if I am correct.

Since you have wrote that I'll wait for a PR and not fix it myself :)

**Comment by mustaphazorgati** [comment]
Just a heads up: Since I think this is a big issue I'll only wait until tomorrow :)

**Comment by dpp23** [comment]
there you go - https://github.com/rokroskar/workflow-run-cleanup-action/pull/30 sorry for the delay should have probably just opened the PR to begin with
