### ISSUE TITLE
[Feature request] macOS support

### ISSUE THREAD

**Issue by Kaspik** [rokroskar/workflow-run-cleanup-action#3]
Hey! It would be great to get this working on `macos-latest` too - currently it fails with `##[error]Container action is only supported on Linux`.

Thanks :)

**Comment by rokroskar** [comment]
It sounds like it's not possible to run docker actions on macos?

**Comment by Kaspik** [comment]
Yes, Docker is not licensing macOS - via https://github.community/t5/GitHub-Actions/Why-is-Docker-not-installed-on-macOS/td-p/39364

I was thikning about trying to find another way how to run the action without Docker?

**Comment by rokroskar** [comment]
It would have to be rewritten as a JavaScript action.

**Comment by n1hility** [comment]
@rokroskar  Hey, sorry to hijack this thread, but just wanted to let you know that I recently published a similar action  (native js version) since I had ran into a similar situation of wanting to limit unnecessary builds. I just stumbled upon this one and wanted to let you know it existed in case it was helpful.

**Comment by rokroskar** [comment]
But you can run each job of the workflow in a different environment so you can easily run this one on Ubuntu and the rest on macos if you want.

**Comment by rokroskar** [comment]
Awesome @n1hility! Thanks for letting me know. Where does it live?

**Comment by Kaspik** [comment]
@n1hility I'm little bit scared of this file - https://github.com/n1hility/cancel-previous-runs/blob/master/dist/index.js - even reading it makes me feel uncomfortable.. 😂 

I'll check both options (run on different machine or another action) - thanks.

**Comment by n1hility** [comment]
@rokroskar sure It's over here: https://github.com/n1hility/cancel-previous-runs

Happy to compare notes or collaborate if you like.

**Comment by rokroskar** [comment]
Btw @n1hility did you find a solution for identifying the workflow id? It was discussed in #1

**Comment by n1hility** [comment]
> @n1hility I'm little bit scared of this file - https://github.com/n1hility/cancel-previous-runs/blob/master/dist/index.js - even reading it makes me feel uncomfortable.. 😂
> 
> I'll check both options (run on different machine or another action) - thanks.

@Kaspik Thats the compiled code, since native actions use typescript, the actual impl is: 
https://github.com/n1hility/cancel-previous-runs/blob/master/src/main.ts

**Comment by n1hility** [comment]
> Btw @n1hility did you find a solution for identifying the workflow id? It was discussed in #1

@rokroskar  Ah yes. I actually query the repo runs endpoint instead of the workflow runs endpoint, and then i filter based off of the workflow url which contains the id, so if workflows happen to be named the same (technically legal) then that still works

**Comment by rokroskar** [comment]
>  I actually query the repo runs endpoint instead of the workflow runs endpoint, and then i filter based off of the workflow url which contains the id

Doh. Of course the workflow id is in that URL. Thanks for the tip!

**Comment by rokroskar** [comment]
Probably won't convert this to a JS action any time soon, so I will close the issue for the time being. It is not actually necessary to run it on macos since this one step can run on any system while the rest of the workflow runs on macos.
