### ISSUE TITLE
Deprecate in favour of `concurrency`

### ISSUE THREAD

**Issue by SimenB** [rokroskar/workflow-run-cleanup-action#33]
GH Actions finally supports this natively 🎉 (I have no idea when support was added, but I just discovered it).

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/

**Comment by jackton1** [comment]
@rokroskar Can we add a deprecation notice, since this is now available natively?

**Comment by rokroskar** [comment]
Indeed thanks @SimenB and @jackton1!

**Comment by mustaphazorgati** [comment]
Added the deprecation warning at the beginning of the README file. 
@rokroskar please check, merge and close this issue. Thanks buddy!
